from django.urls import path
from .views import (
    HealthCheckView,
    LoginView, AdminLoginView, AdminDashboardView, LogoutView, MeView, ChangePasswordView, ForgotPasswordView,
    VerifyResetCodeView, ResetPasswordView, ResendResetCodeView,
    ElectionListView, ElectionDetailView, VoteView, ResultsView, AnalyticsView, VoterAnalyticsView,
    AdminVoterListCreateView, AdminVoterDetailView, AdminVoterPasswordResetView,
    AdminElectionListCreateView, AdminElectionDetailView,
    AdminPositionListCreateView, AdminPositionDetailView,
    AdminCandidateListCreateView, AdminCandidateDetailView, AdminAuditLogListView,
)

urlpatterns = [
    path("health/", HealthCheckView.as_view()),
    path("auth/login/", LoginView.as_view()),
    path("auth/admin/login/", AdminLoginView.as_view()),
    path("auth/logout/", LogoutView.as_view()),
    path("admin/dashboard/", AdminDashboardView.as_view()),
    path("admin/voters/", AdminVoterListCreateView.as_view()),
    path("admin/voters/<int:voter_id>/", AdminVoterDetailView.as_view()),
    path("admin/voters/<int:voter_id>/reset-password/", AdminVoterPasswordResetView.as_view()),
    path("admin/elections/", AdminElectionListCreateView.as_view()),
    path("admin/elections/<int:election_id>/", AdminElectionDetailView.as_view()),
    path("admin/elections/<int:election_id>/positions/", AdminPositionListCreateView.as_view()),
    path("admin/positions/<int:position_id>/", AdminPositionDetailView.as_view()),
    path("admin/elections/<int:election_id>/positions/<int:position_id>/candidates/", AdminCandidateListCreateView.as_view()),
    path("admin/candidates/<int:candidate_id>/", AdminCandidateDetailView.as_view()),
    path("admin/audit-logs/", AdminAuditLogListView.as_view()),
    path("auth/me/", MeView.as_view()),
    path("auth/change-password/", ChangePasswordView.as_view()),
    path("auth/forgot-password/", ForgotPasswordView.as_view()),
    path("auth/resend-code/", ResendResetCodeView.as_view()),
    path("auth/verify-code/", VerifyResetCodeView.as_view()),
    path("auth/reset-password/", ResetPasswordView.as_view()),
    path("elections/", ElectionListView.as_view()),
    path("elections/<int:election_id>/", ElectionDetailView.as_view()),
    path("votes/", VoteView.as_view()),
    path("elections/<int:election_id>/results/", ResultsView.as_view()),
    path("elections/<int:election_id>/analytics/", VoterAnalyticsView.as_view()),
    path("admin/elections/<int:election_id>/analytics/", AnalyticsView.as_view()),
]
