# Generated by Django 5.2.17 on 2026-08-24 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_phase2_database_foundation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('alumni', 'Alumni'), ('faculty', 'Faculty')], db_index=True, help_text='Voter category: Student, Alumni, or Faculty.', max_length=20),
        ),
    ]
